db:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root123
    db_type: mysql
    db_name: panasonic
    
#过滤器
filters:
#为空默认都生成
tables:
#项目名称
projectName: panasonic 
#包名
packageName: com.okycz.panasonic

#源码存放路径
projectPath:
#
controllerPath:
#
servicePath:
#
repositoryPath:
#
modelPath:
#
entityPath:
#
dao_path: