db:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root123
    db_type: mysql
    db_name: kiam_message
    
#过滤器
filters:
#为空默认都生成
tables:
    - tb_email_log
#项目名称
projectName: message-service 
#包名
packageName: com.koal.message

#源码存放路径
projectPath:
#
controllerPath:
#
servicePath:
#
repositoryPath:
#
modelPath:
#
entityPath:
#
dao_path: